### ISSUE TITLE
 Add support for vue router

### ISSUE THREAD

**Issue by vadolasi** [stefanhoelzl/vue.py#10]

**Comment by stefanhoelzl** [comment]
basic support for vue-router is already in.
But there is no documentation for it yet.

You can check out the tests for the vue-router support here
https://github.com/stefanhoelzl/vue.py/blob/master/tests/selenium/test_vuerouter.py
on how to use it.

As I said, only basic support for now, If you need something special please let me know.

**Comment by stefanhoelzl** [comment]
actually there is even documentation for it
https://github.com/stefanhoelzl/vue.py/blob/master/docs/docs/vue_concepts/vue-router.md

it is just not reflected in the official documentation because the router functionality is not in the latest release.
Will release a new version including the router support soon.

**Comment by stefanhoelzl** [comment]
just release version `0.2.0`
official documentation for vue router is now also live
https://stefanhoelzl.github.io/vue.py/docs/vue_concepts/vue-router.html
