### ISSUE TITLE
Relax dependencies

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [stefanhoelzl/vue.py#8]
please make a release with relaxed dependencies, to enable flask 1.1, etc:

https://github.com/stefanhoelzl/vue.py/blob/master/requirements.txt

```
Flask >= 1.0
Jinja2 >= 2.10
pyyaml >= 5.1
```

**Comment by stefanhoelzl** [comment]
I hesitate to change the `requirements.txt`, this file is for specification of the dev environment. This I want to keep stable to avoid issues introduced by implicit changed versions i.e. in a CI run.

But I can change the `setup.py` so that the dependencies are relaxed when you do a `pip install vuepy`

**Comment by Andrei-Pozolotin** [comment]
1. thank you

2. note that `flask`, etc should not be runtime dependency at all for `pip install vuepy`

**Comment by stefanhoelzl** [comment]
> * note that `flask`, etc should not be runtime dependency at all for `pip install vuepy`

this was already done by #3 and will also be available in the next release
